package com.orderfleet.webapp.domain.enums;

public enum CompanyConfig {
	ACCOUNT_PURCHASE_HISTORY_DURATION, COMPANY_PERFORMANCE_BASED_ON, TASK_EXECUTION_OFFLINE_SAVE,
	PROMPT_ATTENDANCE_MARKING, PROMPT_DAYPLAN_UPDATE, PROMPT_MASTERDATA_UPDATE, OTHERVOUCHER_PRINT_VIEW,
	OTHERVOUCHER_EMAIL, ATTENDANCE_MARKING_REQUIRED, DAY_PLAN_DOWNLOAD_REQUIRED, MASTER_DATA_UPDATE_REQUIRED,
	BUILD_DUE_DETAILS, THEME, INCLUDE_ADDRESS_IN_ACCOUNTLIST, USER_WISE, LOCATION_WISE, LOCATION_VARIANCE,
	DISTANCE_TRAVELED, INTERIM_SAVE, REFRESH_PRODUCT_GROUP_PRODUCT, STAGE_CHANGES_FOR_ACCOUNTING_VOUCHER,
	NEW_CUSTOMER_ALIAS, CHAT_REPLY, SALES_PDF_DOWNLOAD, VISIT_BASED_TRANSACTION,SALES_MANAGEMENT,SALES_EDIT_ENABLED,
	GPS_VARIANCE_QUERY;
}
