package com.orderfleet.webapp.domain.enums;

public enum MobileMasterItem {
	
	ACCOUNT_TYPE, ACCOUNT_PROFILE,
	EXECUTIVE_ACTIVITY, ACTIVITY_GROUP, DOCUMENT,
	FORM_ELEMENT_TYPE, FORM_ELEMENTS, FORM,

	FORMS_FORM_ELEMENTS, DOCUMENT_FORMS, DOCUMENT_INVENTORY_VOUCHER_COLUMNS,
	DOCUMENT_ACCOUNTING_VOUCHER_COLUMNS, USER_ACTIVITY_DOCUMENT_DETAILS,
	PRODUCT_CATEGORY, PRODUCT_GROUP,
	PRODUCT_PROFILE, DOCUMENT_PRODUCT_CATEGORY, DOCUMENT_PRODUCT_GROUP,

	ACTIVITY_USER_TARGET, ACTIVITY_GROUP_TARGET, DYNAMIC_FORMULA,
	KNOWLEDGE_BASE, DOCUMENT_ACCOUNT_TYPE, RECEIVABLE_PAYABLE,
	PRODUCT_PRICE_LIST, ACTIVITY_HOUR_PRODUCT_GROUP, COMPETITORS_PROFILE,

	PRICE_TREND_PRODUCT_COMPETITIORS, PRICE_TREND_CONFIGURATION, DOCUMENT_PRICE_LEVELS,
	USER_SALES_TARGET, USER_RECEIPT_TARGET, STOCK_LOCATIONS,
	ACCOUNT_USER_DETIALS, TERRITORY, ROUTE_PLANS,
	MOBILE_SETTING_CONFIG,

	TERRITORY_ACCOUNTG_ASSOCIATION, EMPLOYEE_TERRITORIES, MOBILE_MENU_ITEMS,
	DOCUMENT_SOURCE_STOCK_LOCATIONS, DOCUMENT_DESTGINATION_STOCK_LOCATIONS,
	INCOME_EXPENSE_HEAD, LOCATION_HIRARCHY, ATTENDANCE_SUB_GROUP,
	RECEIVABLE_PAYABLE_COLUMN, ACTIVITY_STAGES, POST_DATED_VOUCHERS,
	VEHICLE_MASTER,DOCUMENT_VOUCHER_NUMBER,
	POST_FCM_KEY,REFERENCE_DOCUMENT,//up to ref_doc we used

	PRODUCT_BATCH_NUMBERS, KNOWLEDGE_BASE_FILE,
	ACTIVITY_ACCOUNT_TYPE, DOCUMENT_PRODUCT_CATEGORY_BY_DOCUMENT_PID,
	DOCUMENT_PRODUCT_GROUP_BY_DOCUMENT_PID, NOTIFICATION,
	DELETE_TASK_EXECUTION, ADVANCED_SEARCH_DOCUMENTS,
	INVENTORY_SEARCH, TEMP_ACTIVITY_DOCUMENT,
	TEMP_INVENTORY_DOCUMENT, FAVORITE,
	DAY_PLAN_EXECUTIVE_CONFIG, ACCOUNT_PURCHASE_HISTORY,
	DAY_PLANS, FEEDBACK_DOCUMENT_DETGAILS,
	ACCOUNT_SALES_TARGET,
	USER_ALL_ACTIVITY_COUNT, PICKING_PACKING;

}
