package com.orderfleet.webapp.domain.enums;

public enum TallyMasters {

	ACCOUNT_PROFILE, PRODUCT_PROFILE, PRODUCT_GROUP, PRODUCT_CATEGORY, TAX_MASTER, LOCATION,
	PRODUCTGROUP_PRODUCTPROFILE, LOCATION_ACCOUNT_PROFILE;
}
